In [1]:
from feature_creation import *

In [2]:
X, y = create_features()

In [7]:
print("Number of features: ", X.shape[1] - 1)

Number of features:  121

In [3]:
X

,prism_consumer_id,CASH MANAGEMENT_cnt,CD_cnt,CHECKING_cnt,CREDIT CARD_cnt,MONEY MARKET_cnt,PREPAID_cnt,SAVINGS_cnt,CREDIT_CARD_PAYMENT,GENERAL_MERCHANDISE,...,LOAN_outflow_over_income,MORTGAGE_outflow_over_income,OVERDRAFT_outflow_over_income,PAYCHECK_outflow_over_income,PETS_outflow_over_income,RENT_outflow_over_income,SELF_TRANSFER_outflow_over_income,TAX_outflow_over_income,TRAVEL_outflow_over_income,UNCATEGORIZED_outflow_over_income
0,0,0,0,1,0,0,0,1,0.054983,0.254435,...,0.339095,0.0,0.000000,0.000000,0.003067,0.000000,0.288454,0.000000,0.007191,0.053970
1,2,0,0,1,0,0,0,1,0.070604,0.040185,...,0.266176,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.117033
2,4,0,0,1,0,0,0,2,0.636902,0.013273,...,0.125352,0.0,0.000000,0.000000,0.000000,0.000000,0.180083,0.000000,0.000000,0.038434
3,7,0,0,2,1,0,0,0,0.165180,0.025106,...,0.260445,0.0,0.001795,0.000000,0.002743,0.000000,0.000000,0.027570,0.043876,0.452855
4,9,0,0,1,0,0,0,0,0.310019,0.148735,...,0.008419,0.0,0.000000,0.000000,0.009310,0.093649,0.005635,0.000000,0.000087,0.116835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2973,5941,0,0,1,0,0,0,0,0.079707,0.172137,...,0.020504,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000123,0.000000,0.136110
2974,5943,0,0,1,0,0,0,0,0.353091,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002107,0.226170
2975,5944,0,0,1,0,0,0,0,0.000000,0.773955,...,0.186571,0.0,0.000000,0.035816,0.000000,0.000000,0.000000,0.000000,0.000000,0.068207
2976,5945,0,0,1,0,0,0,0,0.000000,0.116420,...,0.365438,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.022724,0.009630,0.509051
2977,5949,0,0,1,0,0,0,0,0.048609,0.034987,...,0.001765,0.0,0.001059,0.000000,0.023460,0.000000,0.454444,0.000000,0.007591,0.205165

In [6]:
y

0       0
1       0
2       0
3       0
4       0
       ..
2973    0
2974    0
2975    0
2976    0
2977    0
Name: FPF_TARGET, Length: 2978, dtype: int64